# Generated by Django 3.2 on 2021-04-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('checkout', '0005_order_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.useraccount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.CharField(default='', help_text='No. of items on order', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total before discount IF order qualifies for disount', max_digits=10),
        ),
    ]
