# Generated by Django 3.2 on 2021-04-28 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_auto_20210419_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SavedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(through='saveditems.SavedItems', to='products.Product')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_list', to='accounts.useraccount')),
            ],
        ),
        migrations.AddField(
            model_name='saveditems',
            name='saved_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='saveditems.savedlist'),
        ),
    ]
