# Generated by Django 3.2 on 2021-04-28 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('saveditems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlist',
            name='user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_list', to='accounts.useraccount'),
        ),
    ]
