# Generated by Django 3.2 on 2021-04-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210419_1611'),
        ('saveditems', '0002_alter_savedlist_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveditems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_list', to='products.product'),
        ),
        migrations.AlterField(
            model_name='saveditems',
            name='saved_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_list', to='saveditems.savedlist'),
        ),
        migrations.AlterField(
            model_name='savedlist',
            name='items',
            field=models.ManyToManyField(related_name='saved_items', through='saveditems.SavedItems', to='products.Product'),
        ),
    ]
