# Generated by Django 3.2 on 2021-04-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='bag_size',
            field=models.CharField(choices=[('250g', '250 grams'), ('500g', '500 grams')], default='250g', max_length=4),
            preserve_default=False,
        ),
    ]
